title: "Rajesh RR — Delivery, AI & Automation"
description: "AI-powered delivery insights, leadership notes, and practical automation."
theme: minima           # or jekyll-theme-cayman / jekyll-theme-midnight
logo: /assets/hero.png   # optional
show_downloads: false
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
author:
  name: "Rajesh RR"
  url: "https://www.linkedin.com/in/rajeshrr/"
url: "https://rcube9.github.io"
baseurl: "/ProAIInsights"   # important for project sites
permalink: /posts/:title/
header_pages:
  - blog.md
